# Generated by Django 5.2.9 on 2025-12-22 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', '🆕New🆕'), ('in_progress', '👨\u200d💻In Progress👨\u200d💻'), ('closed', '🔒Closed🔒'), ('waiting', '💤Waiting💤')], default='New')),
                ('description', models.CharField(blank=True)),
                ('priority', models.CharField(choices=[('critical', '🔥Critical🔥'), ('high', '\U0001fae8Important\U0001fae8'), ('medium', '🍃Medium🍃'), ('low', '🤓Low🤓')], default='medium')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
